# Generated by Django 4.2.6 on 2023-10-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bb',
            new_name='Bboard',
        ),
    ]
